### PR TITLE
Project JAR

### PR DESCRIPTION
**Pull request by rcantware**
Test the ".jar" to make sure everything works properly.

https://github.com/WindowDump/CS225-March-Madness/blob/038357e38c70e82ab4da1a4f71805ae2f55ea590/CS225-March-Madness.jar

### CODE REVIEW

**Comment by WindowDump** [comment]
I can't seem to get it to save any brackets.

**Comment by rcantware** [comment]
It seems to save brackets for me

**Comment by rcantware** [comment]
It only serializes if you complete the bracket and select finalize.

**Comment by WindowDump** [comment]
Strange - I tried it again and it worked fine.

**Pull request merged**
